/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QzqnUTA88tk
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { ResponsiveLine } from "@nivo/line"

export function Whole() {
  return (
    (<Card className="w-full max-w-2xl">
      <CardHeader className="flex items-center justify-between gap-4 pb-4">
        <div className="grid gap-1">
          <div className="text-lg font-semibold">Stock Lookup</div>
          <div
            className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
            Enter a stock ID or tag to get details
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <div className="grid gap-4">
          <div className="relative">
            <Input className="pr-[120px]" placeholder="Enter stock ID or tag" />
            <Button className="absolute top-1/2 right-2 -translate-y-1/2">Search</Button>
          </div>
          <div className="flex items-center justify-between">
            <div className="font-medium">Stock Price</div>
            <div className="font-medium">$159.24</div>
          </div>
          <div className="flex items-center justify-between">
            <div className="font-medium">52-Week Range</div>
            <div className="font-medium">$120.67 - $176.42</div>
          </div>
          <div className="flex items-center justify-between">
            <div className="font-medium">Market Cap</div>
            <div className="font-medium">$2.57T</div>
          </div>
          <div className="mt-6">
            <LineChart className="aspect-[9/4]" />
          </div>
        </div>
      </CardContent>
    </Card>)
  );
}

function LineChart(props) {
  return (
    (<div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "Desktop",
            data: [
              { x: "Jan", y: 43 },
              { x: "Feb", y: 137 },
              { x: "Mar", y: 61 },
              { x: "Apr", y: 145 },
              { x: "May", y: 26 },
              { x: "Jun", y: 154 },
            ],
          },
          {
            id: "Mobile",
            data: [
              { x: "Jan", y: 60 },
              { x: "Feb", y: 48 },
              { x: "Mar", y: 177 },
              { x: "Apr", y: 78 },
              { x: "May", y: 96 },
              { x: "Jun", y: 204 },
            ],
          },
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
        }}
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        colors={["#2563eb", "#e11d48"]}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application" />
    </div>)
  );
}
